// Mocks generated by Mockito 5.4.0 from annotations
// in mobile/test/features/todo/data/repositories/todo_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile/core/network/network_info.dart' as _i3;
import 'package:mobile/features/todo/data/datasources/todo_remote_datasource.dart'
    as _i5;
import 'package:mobile/features/todo/domain/entities/todo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodoEntity_0 extends _i1.SmartFake implements _i2.TodoEntity {
  _FakeTodoEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [TodoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRemoteDataSource extends _i1.Mock
    implements _i5.TodoRemoteDataSource {
  @override
  _i4.Future<_i2.TodoEntity> createTodo(
    String? title,
    bool? completed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTodo,
          [
            title,
            completed,
          ],
        ),
        returnValue: _i4.Future<_i2.TodoEntity>.value(_FakeTodoEntity_0(
          this,
          Invocation.method(
            #createTodo,
            [
              title,
              completed,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TodoEntity>.value(_FakeTodoEntity_0(
          this,
          Invocation.method(
            #createTodo,
            [
              title,
              completed,
            ],
          ),
        )),
      ) as _i4.Future<_i2.TodoEntity>);
  @override
  _i4.Future<List<_i2.TodoEntity>> getAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #getAllTodos,
          [],
        ),
        returnValue: _i4.Future<List<_i2.TodoEntity>>.value(<_i2.TodoEntity>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.TodoEntity>>.value(<_i2.TodoEntity>[]),
      ) as _i4.Future<List<_i2.TodoEntity>>);
  @override
  _i4.Future<_i2.TodoEntity> updateTodo(
    String? id,
    String? title,
    bool? completed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [
            id,
            title,
            completed,
          ],
        ),
        returnValue: _i4.Future<_i2.TodoEntity>.value(_FakeTodoEntity_0(
          this,
          Invocation.method(
            #updateTodo,
            [
              id,
              title,
              completed,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TodoEntity>.value(_FakeTodoEntity_0(
          this,
          Invocation.method(
            #updateTodo,
            [
              id,
              title,
              completed,
            ],
          ),
        )),
      ) as _i4.Future<_i2.TodoEntity>);
  @override
  _i4.Future<_i2.TodoEntity> deleteTodo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodo,
          [id],
        ),
        returnValue: _i4.Future<_i2.TodoEntity>.value(_FakeTodoEntity_0(
          this,
          Invocation.method(
            #deleteTodo,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TodoEntity>.value(_FakeTodoEntity_0(
          this,
          Invocation.method(
            #deleteTodo,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.TodoEntity>);
}
